pipeline:
  name: Tetris CI
  identifier: pipeline2
  orgIdentifier: default
  projectIdentifier: default_project
  stages:
    - stage:
        name: Build and E2E
        identifier: BuildAndE2E
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Install dependencies
                  identifier: InstallDeps
                  spec:
                    connectorRef: account.harnessImage
                    image: node:20
                    command: |
                      npm ci
              - step:
                  type: Run
                  name: Build Next.js
                  identifier: BuildNext
                  spec:
                    connectorRef: account.harnessImage
                    image: node:20
                    command: |
                      npm run build
              - step:
                  type: Run
                  name: Install Playwright browsers
                  identifier: InstallPlaywrightBrowsers
                  spec:
                    connectorRef: account.harnessImage
                    image: node:20
                    command: |
                      npx playwright install --with-deps
              - step:
                  type: Run
                  name: Run Playwright E2E
                  identifier: RunPlaywrightE2E
                  spec:
                    connectorRef: account.harnessImage
                    image: node:20
                    command: |
                      export CI=true
                      npm run test:e2e
  properties:
    ci:
      codebase:
        connectorRef: account.github
        repoName: tetris
        build:
          type: branch
          spec:
            branch: <+input>
