pipeline:
  name: pipeline2
  identifier: pipeline2
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: wut
        identifier: wut
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: Email
                  name: Email_1
                  identifier: Email_1
                  spec:
                    to: jonathan.weber@harness.io
                    cc: ""
                    subject: hello world
                    body: pipeline2/tetris project
                  timeout: 10m
        tags: {}
